from ase import Atoms
from ase.io import read, write
import mdtraj as mdt
import numpy as np
from scipy.spatial.distance import pdist
import subprocess


def compute_all_rdfs(trj, n_bins=150, is_save_rdf=True, **kwargs):
    """Computes the RDFs between all pairs of atom types in a trajectory.
        https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.compute_rdf.html#mdtraj.compute_rdf

       input:
       trj: (mdtraj object) A trajectory from MD simulation
       n_bins: (int) Number of bins used for the RDF

       output:
       rdfs_all: (dictionary) RDFs for all paris

    """

    top = trj.topology

    rdfs_all = {}

    # Determine the unique atom types
    atom_types = get_unique_atom_types(trj.topology)

    for i1, t1 in enumerate(atom_types):

        # select indices of the first atom type
        idx_t1 = top.select('name ' + t1)

        # unique atom type pairs only
        for i2 in range(i1, len(atom_types)):

            t2 = atom_types[i2]

            # select indices of the second atom type
            idx_t2 = top.select('name ' + t2)

            # prepare all pairs of indices
            pairs = trj.topology.select_pairs(idx_t1, idx_t2)

            # single atom with itself -> no RDF
            if len(pairs) == 0:
                continue

            # OM: not sure this should be done here
            min_dimension = trj[0].unitcell_lengths.min() / 2
            # print(min_dimension)

            r, g_r = mdt.compute_rdf(
                trj, pairs,
                (0, min_dimension), n_bins=n_bins, **kwargs
            )

            rdfs_all[t1 + '-' + t2] = r, g_r
            if is_save_rdf:
                np.savetxt('g' + str(t1) + '-' + str(t2) + '.dat', np.vstack([r, g_r]).T)

    return rdfs_all


def compute_hydrodynamic_radius(trj):
    """Compute hydrodynamic radius (Rh) using Kirkwood definition.
       https://en.wikipedia.org/wiki/Hydrodynamic_radius

       input:
       trj: (mdtraj object) A trajectory from MD simulation

       output:
       Rh_list: (float) hydrodynamic radius in angstrom along the whole trajectory

    """
    # Preset empty list for Rh intake
    Rh_list = []
    
    # Load in coordinate along the whole trajectory
    full_coordinate = trj.xyz
    
    for i in range(full_coordinate.shape[0]):
        
        # Derive number of atoms
        number_of_atoms = full_coordinate[i].shape[0]

        # Calculate ensemble average of the inverse distance
        coordinate_in_angstrom = 10.0 * full_coordinate[i]
        pair_wise_distances = pdist(coordinate_in_angstrom)
        inverse_distances = 1 / pair_wise_distances

        # Clean up diagonal of inverse distances and
        # compute ensemble average
        #np.fill_diagonal(inverse_distances, 0)
        ensemble_average_inverse_distances = inverse_distances.sum()

        # Express Rh
        Rh = 2 * number_of_atoms ** 2 / ensemble_average_inverse_distances
        Rh_list.append(Rh)
    return Rh_list


def decompose_dump_xyz(dump_xyz_str, pos_xyz_str='pos.xyz',
                       frc_xyz_str='frc.xyz',
                       vel_xyz_str='vel.xyz'):
    """Decompose information from dump.xyz, generated by GPUMD.
       https://gpumd.zheyongfan.org/index.php/The_dump_exyz_keyword

       input:
       dump_xyz_str: (str) Name of the dump xyz file
       pos_xyz_str: (str) Name of the pos xyz file
       pos_xyz_str: (str) Name of the force/frc xyz file
       vel_xyz_str: (str) Name of the  velocity/vel xyz file

    """
    # Load in static information
    configurations = read(dump_xyz_str, index=':')
    chemical_symbols = configurations[0].get_chemical_symbols()

    # Preset list for sudo atom objects for positions, forces and velocities
    pos_atom_objects = []
    frc_atom_objects = []
    vel_atom_objects = []

    # Decompose position, force and velocity information into lists individually
    for configuration in configurations:
        pos_atom_objects.append(make_atom_object(chemical_symbols, configuration.positions, configuration.cell))
        frc_atom_objects.append(make_atom_object(chemical_symbols, configuration.arrays['forces'], configuration.cell))
        vel_atom_objects.append(make_atom_object(chemical_symbols, configuration.arrays['vel'], configuration.cell))

    # Write individual information into xyz file
    write(pos_xyz_str, pos_atom_objects)
    write(frc_xyz_str, frc_atom_objects)
    write(vel_xyz_str, vel_atom_objects)


def get_quantity_averages(quantities, mode='diff'):
    """Get averages of quantity derived from MD simulation

       input:
       quantities: (ndarray) quantity derived from MD simulation
       mode: (str) different modes to take averages

       output:
       average: (float) average of quantities
    """

    if mode not in ['all', 'diff']:
        print('Only "all" or "diff" are valid mode strings!')
        exit()

    if mode == 'all':
        return np.mean(quantities)

    if mode == 'diff':
        # Find where to perform average by using derivatives
        rate_of_change_quantities = np.diff(quantities)
        max_change = np.abs(rate_of_change_quantities).max()

        # 10 % of max change is used as the standard
        index = np.where(np.abs(
            rate_of_change_quantities) <= 0.01 * max_change)[0][0]

    return np.mean(quantities[index:])


def grep_from_md_output(md_output_file_name, time_step_in_ps, total_number_of_steps, patten_str, row_index_to_skip=0):
    """Grep several observables from snap md output

       input:
       md_output_file_name: (str) file name of the md output
       time_step_in_ps: (float) time step in ps
       total_number_of_steps: (int) total number of time steps

       output:
       data: (numpy array) data parsed from the md output

    """

    # Create key variable for the command line
    # + 1 for the header
    total_number_of_lines_to_grep = int(time_step_in_ps * total_number_of_steps + 1)

    # Generate a cmd pattern
    cmd = "grep -A " + str(total_number_of_lines_to_grep) + "pattern " + md_output_file_name + ">" + "tmp.out"
    cmd_full = cmd.replace("pattern", patten_str)
    subprocess.call(cmd_full, shell=True)

    try:
        data = np.loadtxt('tmp.out', skiprows=row_index_to_skip)
    except (ValueError, FileNotFoundError, IndexError):
        print('Data can not be properly loaded! Check file manually for more details.')

    return data


def get_unique_atom_types(topology):
    """Obtain unique atom types from a reference topology.

       input:
       topology: (pdb) Reference topology, often in a format of pdb

       output:
       atom_types: (list) List of unique atom type strings
    """
    atom_types = list(set(atom.name for atom in topology.atoms))

    return atom_types


def load_nth_frames(total_xyz_name, reference_chemical_symbols, frame_index=-1, frame_output_format='pdb'):
    """Load nth frame from the xyz output dumped from lammps simulation

       input:
       total_xyz_name: (str) name of the lammps dumped xyz file
       frame_index: (int) index to signify which frame to take from md
       reference_chemical_symbols: (nd str array) nd string array
       frame_output_format: (str) format of the output frames

       output:
       coordinate of nth frame in specific format

    """

    # Load in the whole configuration and extract specific frames
    configurations = read(total_xyz_name, index=':', format='lammps-dump-text')
    selected_frames = configurations[frame_index]

    # Fix misread issue, workable even it does not happen
    if type(frame_index) != int:
        for i in range(len(selected_frames)):
            selected_frames[i].set_chemical_symbols(reference_chemical_symbols)
            selected_frames[i].set_pbc([True, True, True])

    else:
        selected_frames.set_chemical_symbols(reference_chemical_symbols)
        selected_frames.set_pbc([True, True, True])
    if frame_output_format == '.lmp':
        write('extracted_frames' + frame_output_format, selected_frames, format='lammps-data')
    else:
        write('extracted_frames' + frame_output_format, selected_frames)


def load_with_cell(filename, unitcell_length_matrix, unitcell_angle_matrix,
                   start=None, stop=None, step=None, **kwargs):
    """Load a trajectory and inject cell dimensions from a topology PDB file if not present.
    All arguments and keyword arguments are passed on to `mdtraj.load`. The `top`
    keyword argument is used load a PDB file and get cell information from it.

    input:
    file_name (str):

    """
    # load the "topology frame" to get cell dimensions
    top = kwargs.get("top")
    if top is not None and isinstance(top, str):
        # load topology frame - just the first one from the file, in case there are more frames
        frame_top = mdt.load_frame(top, 0)
        unitcell_lengths = frame_top.unitcell_lengths
        unitcell_angles = frame_top.unitcell_angles
        if (unitcell_lengths is None) or (unitcell_angles is None):
            raise ValueError("Frame providing topology is missing cell information.")
    else:
        raise ValueError("Provide a PDB with cell dimensions.")

    # load the trajectory itself
    trj = mdt.load(filename, **kwargs)
    trj = trj[start:stop:step]

    # inject the cell information
    trj.unitcell_lengths = unitcell_length_matrix
    trj.unitcell_angles = unitcell_angle_matrix

    return trj


def make_atom_object(atomic_string, coordinate, cell):
    """Create simple atom object based on chemical symbol and "position-like" vectors

           input:
           atomic_string: (nd str array) nd string array
           coordinate: (nd float array) "position-like" vector

           output:
           atoms (ASE Atoms object): atom object

    """
    # Build ase atom object from starch
    tmp_str = 'H' * len(atomic_string)

    # Ghost molecule!
    atoms = Atoms(tmp_str)

    # Inheritance properties from input
    atoms.set_chemical_symbols(atomic_string)
    atoms.set_positions(coordinate)
    atoms.set_pbc([True, True, True])
    atoms.cell = cell
    return atoms


def process_diffusion_coefficients(sdc_out_str, dimension_factor=3,
                                   is_verbose=True):
    """Process self-diffusion coefficients computed from GPUMD

       input:
       sdc_out_str: (str) name of the sdc file
       dimension factor: (int) dimension factor, 3 for all 3 dimensions
       is_verbose: (bool) whether to print out fitted diffusion coefficients

       output:
       D: (float) Diffusion coefficients in 10^-5 cm^2/s
    """
    # Load in data from sdc.out
    data = np.loadtxt(sdc_out_str)

    # Extract correlation time and self-diffusion coefficients along each direction
    correlation_time = data[:, 0]
    D_x = data[:, 4]
    D_y = data[:, 5]
    D_z = data[:, 6]

    # Obtain average along each direction
    # 10.0 makes it goes from A^2/ps to 10^-5 cm^2/s
    D = 10.0 * (get_quantity_averages(D_x) + get_quantity_averages(D_y) + get_quantity_averages(D_z)) / dimension_factor

    # Display results in original form:
    # 10.0 makes it goes from A^2/ps to 10^-5 cm^2/s
    if is_verbose:
        print('Diffusion coefficients in 10^-5 cm^2/s: %.1f' % D)
    return D, D_x, D_y, D_z, correlation_time


def score_property(prediction, ground_truth, tolerance, property_str):
    """Score static property of water using the score function
       from Carlos Vega et al.
       DOI: 10.1039/c1cp22168j

       input:
       prediction: (float) predicted property from snap md
       ground_truth: (float) experimental properties
       tolerance: (float) tolerance factor in %
       property_str: (str) name of predicted property

       output:
       final score: (int) final score of the property,

    """
    base_score = np.round(10 - np.abs(100 * (
            prediction - ground_truth) / (ground_truth * tolerance)))
    final_score = np.max([base_score, 0])
    print('Predicted ' + property_str + ' earned a score of %d' % final_score)

    return final_score

